GET http://localhost:5023/games

###
GET http://localhost:5023/games/2


###
POST  http://localhost:5023/games
Content-Type: application/json

{
    "name" : "Fire Emblem Path of Radiance",
    "genreId" : 2,
    "Price" : 150.99,
    "releaseDate" : "2006-04-20"
}

###
PUT  http://localhost:5023/games/2
Content-Type: application/json

{
    
    "name" : "Fire Emblem Radiant dawn",
    "genreId" : 2,
    "Price" : 150.99,
    "releaseDate" : "2006-04-20"
}

###
DELETE http://localhost:5023/games/2